### ISSUE TITLE
Implement relaton-ccsds for www.ccsds.org Standards

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ccsds#1]
CCSDS is the SDO on space standards.

CCSDS publishes the following types of standards:
* CCSDS Recommended Standards (Blue Books)
* CCSDS Recommended Practices (Magenta Books)
* CCSDS Informational Reports (Green Books)
* CCSDS Experimental Specification (Orange Books)
* CCSDS Record documents (Yellow Books)

Then they have retired documents called:
* CCSDS Historical designation (Silver Books)

Metadata of all publications is available from this page (set to "Show ALL") (only missing retired documents):
* https://public.ccsds.org/Publications/AllPubs.aspx

Silver Books are available from:
* https://public.ccsds.org/Publications/SilverBooks.aspx

Now, being a "Silver Book" we need to work out what type of document it originally was. Luckily, the CCSDS identifiers tell us exactly what type of document it was.

<img width="1145" alt="Screen Shot 2022-08-24 at 12 52 25 PM" src="https://user-images.githubusercontent.com/11865/186331796-bf2b9c18-6bd1-4afb-8060-515d6e7d862f.png">

e.g. 
* "CCSDS 100.0-G-1-S" the "G" indicates that it was a "Green Book", i.e. "Informational Report".
* "CCSDS 101.0-B-1-S" is a "B" so it was a "Blue Book", i.e. "Recommended Standard".

<img width="1025" alt="Screen Shot 2022-08-24 at 1 33 32 PM" src="https://user-images.githubusercontent.com/11865/186337091-00dfd651-138a-4f4f-8224-b9f45bd06065.png">

The metadata of each entry includes:
* PubId: CCSDS 141.1-M-1
* Title: Atmospheric Characterization and Forecasting for Optical Link Operations
* Document type: Magenta Book
* Issue number / Edition: 1
* Publication date: 2022-01
* Description: This Recommended Practice provides a set of recommendations to facilitate interagency collection of atmospheric data and characterization of atmospheric parameters that affect space-to-ground free-space optical communications.
* Working Group: SLS-OPT
* Document link: https://public.ccsds.org/Pubs/141x1m1.pdf

Some Blue Books have links to ISO:
<img width="665" alt="Screen Shot 2022-08-24 at 1 36 23 PM" src="https://user-images.githubusercontent.com/11865/186337467-0daace8e-aaf0-4cf0-a990-9d8ee6a30aa3.png">

* ISO Equivalent: 15887 (i.e. "ISO 15887"), with link

Some documents are Corrigenda:
<img width="695" alt="Screen Shot 2022-08-24 at 1 37 52 PM" src="https://user-images.githubusercontent.com/11865/186337661-e8e5d37e-0f47-4ed4-b714-3931e112ae08.png">
* PubId: CCSDS 123.0-B-2 Cor. 2
* Issue Number: 2 Cor. 2
* We need to create a relation back to the document to be corrected (i.e. "CCSDS 123.0-B-2")

Some documents require patent licensing:
<img width="702" alt="Screen Shot 2022-08-24 at 1 39 16 PM" src="https://user-images.githubusercontent.com/11865/186337857-c3583092-ae91-4bb7-837c-4623e2ab9d6d.png">

* IPR: Patent Licensing. (with https link)

CCSDS documents are further grouped into Areas:
<img width="727" alt="Screen Shot 2022-08-24 at 1 40 57 PM" src="https://user-images.githubusercontent.com/11865/186338673-cf5731cf-1711-4e7b-beed-ae195feb773f.png">
* Space Internetworking Services (SIS)
* Mission Ops. And Information Management Services (MOIMS)
* Spacecraft Onboard Interface Services (SOIS)
* System Engineering (SE)
* Cross Support Services (CSS)
* Space Link Services (SLS)

The area of a document can be known by the responsible Working Group. e.g. "MOIMS-NAV" means the "MOIMS" area in the "NAV" working group.

The full list of working groups is available here:
https://cwe.ccsds.org/default.aspx

Within each area there are:
* Working Groups (WG)
* Birds of a Feather (BOF)
* Special Interest Groups (SIG)

Groups (above Areas):
* CCSDS Management Council (CMC)
* CCSDS Engineering Steering Group (CESG)

Areas:
* Systems Engineering Area (SEA)
  * Systems Architecture Working Group (SEA-SA)
  * Security Working Group (SEA-SEC)
  * Delta-DOR Working Group (SEA-D-DOR)
  * Time Management Working Group (SEA-TIME)
* Mission Operations and Information Management Services Area (MOIMS)
  * Data Archive Interoperability Working Group (MOIMS-DAI)
  * Navigation Working Group (MOIMS-NAV)
  * Spacecraft Monitor and Control Working Group (MOIMS-SM&C)
  * Mission Planning & Scheduling Working Group (MOIMS-MP)
* Cross Support Services Area (CSS)
  * Service Management Working Group (CSS-SM)
  * Transfer Services Working Group (CSS-CSTS)
  * Cloud Computing Birds of a Feather (CSS-CLOUD)
* Spacecraft Onboard Interface Services Area (SOIS)
  * Application Support Services Working Group (SOIS-APP)
  * Onboard Wireless Working Group (SOIS-WIR)
  * Subnetwork Services Working Group (SOIS-SUBNET)
* Space Link Services Area (SLS)
  * RF Modulation Working Group (SLS-RFM)
  * Space Link Coding and Synchronization Working Group (SLS-C&S)
  * Data Compression Working Group (SLS-DC)
  * Space Link Protocols Working Group (SLS-SLP)
  * Space Data Link Layer Security Working Group (SLS-SEA-DLS)
  * Optical Communications Working Group (SLS-OPT)
* Space Internetworking Services Area (SIS)
  * Motion Imagery and Applications Working Group (SIS-MIA)
  * Delay Tolerant Networking Working Group (SIS-DTN)
  * Voice Working Group (SIS-VOICE)
  * CCSDS CFDP Revisions Working Group (SIS-CFDPV1)

What we need to do:
* Create relator-model-ccsds to encode these items
* Create pubid-ccsds to parse these pubids
* Create and build a `relaton-data-ccsds` repository to make these documents citable.

**Comment by ronaldtse** [comment]
https://github.com/metanorma/iso-14812/issues/5 requires implementation of this.

**Comment by CAMOBAP** [comment]
Boilerplate was generated to add CI

**Comment by andrew2net** [comment]
@ronaldtse do we need to store in our data-model full area names, i.e. "Mission Operations and Information Management Services", or just an abbreviation, i.e. "MOIMS"?

**Comment by andrew2net** [comment]
> Some Blue Books have links to ISO:

@ronaldtse how should we process the ISO links? Are they relations? If they are, what type are the relations?
Maybe they are link. If so, what type are they?

**Comment by ronaldtse** [comment]
> @ronaldtse do we need to store in our data-model full area names, i.e. "Mission Operations and Information Management Services", or just an abbreviation, i.e. "MOIMS"?

Yes, because the reading software would likely not have this information, and become unable to render the name.

> > Some Blue Books have links to ISO:
> 
> @ronaldtse how should we process the ISO links? Are they relations? If they are, what type are the relations? Maybe they are link. If so, what type are they?

(Remember historic items "Silver Books" can also be "retired Blue Books" and therefore have an ISO equivalent)

These ISO documents are Blue Books adopted by ISO, meaning that they are the Relaton `adoptedBy:equivalent` relationship (https://www.relaton.org/specs/model/relations/).

**Comment by andrew2net** [comment]
@ronaldtse It seems the spec https://www.relaton.org/specs/model/relations/ diverges from the [grammar](https://github.com/relaton/relaton-models/blob/d7115ee43416a2d3bd0b050cda687504282f247e/grammars/biblio.rnc#L436). I think we can use `adoptedAs` in this case, do we? What does `equivalent` means in `adoptedBy:equivalent`?

**Comment by ronaldtse** [comment]
The Relaton model is the authoritative source. The grammar is supposed to derive from it.

"equivalent" means it is a document that is meant to do the same thing. Yes, the Relaton relations of `adoptedFrom` or `adoptedAs` (different directions) are the correct relations.

**Comment by andrew2net** [comment]
@ronaldtse I'm sure we need only one direction `adoptedAs` since the relation to another dataset. See [example](https://github.com/relaton/relaton-data-ccsds/blob/603be50f71fa7c9a4c859ea413dc26e66d4772ae/data/CCSDS-650-0-B-1.yaml#L48).

**Comment by ronaldtse** [comment]
@andrew2net yes only one direction: CCSDS standard "adoptedAs" ISO standard. Thanks. Can we close this now?

**Comment by andrew2net** [comment]
Yes, closing.

**Comment by ronaldtse** [comment]
Thank you @andrew2net !
